[tsne][SYCL] Use property_list instead of property value
Fix the initialisation of the reduction object by passing
a property list rather than a single property. The latter
fails in newer DPC++ versions with:
error: no member named 'has_property' in 'sycl::property::reduction::initialize_to_identity'