[hplinpack][SYCL] Fix the use of deprecated namespace
The use of `cl::sycl::` in place of `sycl::` is deprecated
in SYCL2020 and causes the compilation to fail in recent
DPC++ versions with:

error: use of undeclared identifier 'cl'

Fix this by using just the `sycl::` namespace.